### ISSUE TITLE
Tooltips are a couple of pixels off

### ISSUE THREAD

**Issue by tpetricek** [jet/FsBlog#2]
The same thing happened to me in another project - it happens when you have tooltips in a HTML element that has `position:relative`. The way to fix this is to check for this in the `findPos` function in `tooltips.js`. See [this implementation](https://github.com/tpetricek/FsSnip.Website/blob/master/web/content/tips.js#L14).

The only reason why I did not send a PR is that I have not figure out how to check if position is `relative` without JQuery. The code I linked uses JQuery - so you can either add reference to JQuery, or figure out how to do this better :-)

**Comment by tpetricek** [comment]
(Also, it might be worth sending a PR with the fix to FsProjects - this would be a great improvement!)

**Comment by rachelreese** [comment]
You're completely right that I should figure this out properly and send a PR back to the original FsBlog. But it turns out that setting ``position:relative`` on the main content isn't actually needed, and solves the problem. It's cheating a bit, but the issue is solved. ;-)

**Comment by tpetricek** [comment]
Haha, that was my first thought when I had the issue. Well, *somebody* should figure this out :)
