### ISSUE TITLE
Adding a .ToString to a date in one file (but not another) causes FSharp.Core mismatch errors 

### ISSUE THREAD

**Issue by rachelreese** [jet/FsBlog#4]
For awhile, it's been bugging me that on the main page of the blog, the tagline pretty-prints the date, e.g.: 

> "Gene Belitski    |     Jan 30, 2016   |   f#, interview   |    We're hiring: Director, Engineering (Dublin)!" 
[(page layout file](https://github.com/jet/FsBlog/tree/master/Code/content/layouts/page.cshtml"))

but when you click in to the post, it reads: 

> "Gene Belitski    |     2016-01-30T03:49:06   |   F#, interview" 
([post layout file](https://github.com/jet/FsBlog/tree/master/Code/content/layouts/post.cshtml))

I tried copy-pasting the entire `@tagline` section of code, but kept getting errors. Tracked it down. Specifically, when I try to update this line, in the post layout file: 

`@AddedDate`
to 
`@AddedDate.ToString("MMM d, yyyy")`

I receive the following error. The weird thing is, it obviously works fine in the page layout file, so what the heck? 

```
Something went wrong: RazorEngine.Templating.TemplateCompilationException: Unable to compile template. Assuming assembly 
reference 'FSharp.Core, Version=4.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' matches 'FSharp.Core, Version=
4.3.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a', you may need to supply runtime policy                        
                                                                                                                         
Other compilation errors may have occurred. Check the Errors property for more information.                              
   at RazorEngine.Compilation.DirectCompilerServiceBase.CompileType(TypeContext context) in c:\_git\RazorEngine\src\Core\
RazorEngine.Core\Compilation\DirectCompilerServiceBase.cs:line 106                                                       
   at RazorEngine.Templating.TemplateService.CreateTemplateType(String razorTemplate, Type modelType) in c:\_git\RazorEng
ine\src\Core\RazorEngine.Core\Templating\TemplateService.cs:line 256                                                     
   at RazorEngine.Templating.TemplateService.GetTemplate[T](String razorTemplate, Object model, String cacheName) in c:\_
git\RazorEngine\src\Core\RazorEngine.Core\Templating\TemplateService.cs:line 374                                         
   at RazorEngine.Templating.TemplateService.Resolve(String cacheName, Object model) in c:\_git\RazorEngine\src\Core\Razo
rEngine.Core\Templating\TemplateService.cs:line 570                                                                      
   at RazorEngine.Templating.TemplateBase.RazorEngine.Templating.ITemplate.Run(ExecuteContext context) in c:\_git\RazorEn
gine\src\Core\RazorEngine.Core\Templating\TemplateBase.cs:line 0                                                         
   at FsBlogLib.Razor.ProcessFile(String source) in C:\Users\jetadmin\GitHub\Jet Code\FsBlog\Code\tools\FsBlogLib\Razor.f
s:line 54
```

Halp? @tpetricek, @robertpi (since you've contributed to FsBlog recently, :) ) 

Not sure who to tag on this one, or where even to start tracking it down from here, so feel free to tag away. :-) Thanks!

**Comment by robertpi** [comment]
These razor files are a bit black magic, unfortunately. At a guess
"@AddedDate" is typed as object, so it can't find the format
overload when you try and call the ToString method? I notice the way
the that works uses a help function to format the string, could you
copy past that?

A cleaner way might be to get the model that provides @AddedDate to do
the formating before it's passed to razor, but I've know idea which
model provides @AddedDate.

Cheers, Rob


On Sun, Feb 21, 2016, at 12:58 PM, Rachel Reese wrote:
> For awhile, it's been bugging me that on the main page of the blog,
> the tagline pretty-prints the date, e.g.:


>> "Gene Belitski    |     Jan 30, 2016   |   f#, interview   |    We're
>> hiring: Director, Engineering (Dublin)!" (page layout file[1])


> but when you click in to the post, it reads:


>> "Gene Belitski    |     2016-01-30T03:49:06   |   F#, interview"
>>
(post layout file[2])


> I tried copy-pasting the entire @tagline section of code, but kept
> getting errors. Tracked it down. Specifically, when I try to update
> this line, in the post layout file:


> @AddedDate
>
to
> @AddedDate.ToString("MMM d, yyyy")


> I receive the following error. The weird thing is, it obviously works
> fine in the page layout file, so what the heck?


> `Something went wrong:
> RazorEngine.Templating.TemplateCompilationException: Unable to compile
> template. Assuming assembly
>
reference 'FSharp.Core, Version=4.3.0.0, Culture=neutral,
PublicKeyToken=b03f5f7f11d50a3a' matches 'FSharp.Core, Version=
>
4.3.1., Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a', you may need
      to supply runtime policy


> Other compilation errors may have occurred. Check the Errors property
> for more information.
>
>
   at RazorEngine.Compilation.DirectCompilerServiceBase.CompileType(Typ-
   eContext context) in c:_git\RazorEngine\src\Core\
>
RazorEngine.Core\Compilation\DirectCompilerServiceBase.cs:line 106
>
>
   at RazorEngine.Templating.TemplateService.CreateTemplateType(String
   razorTemplate, Type modelType) in c:_git\RazorEng
>
ine\src\Core\RazorEngine.Core\Templating\TemplateService.cs:line 256
>
>
   at RazorEngine.Templating.TemplateService.GetTemplateT in c:_
>
git\RazorEngine\src\Core\RazorEngine.Core\Templating\TemplateService.c-
s:line 374
>
>
   at RazorEngine.Templating.TemplateService.Resolve(String cacheName,
   Object model) in c:_git\RazorEngine\src\Core\Razo
>
rEngine.Core\Templating\TemplateService.cs:line 570
>
>
   at RazorEngine.Templating.TemplateBase.RazorEngine.Templating.ITempl-
   ate.Run(ExecuteContext context) in c:_git\RazorEn
>
gine\src\Core\RazorEngine.Core\Templating\TemplateBase.cs:line 0
>
>
   at FsBlogLib.Razor.ProcessFile(String source) in
   C:\Users\jetadmin\GitHub\Jet Code\FsBlog\Code\tools\FsBlogLib\Razor.f
>
s:line 54`


> Halp? @tpetricek[3], @robertpi[4] (since you've contributed to FsBlog
> recently, :) )


> Not sure who to tag on this one, or where even to start tracking it
> down from here, so feel free to tag away. :-) Thanks!


> — Reply to this email directly or view it on GitHub[5].


>



Links:

  1. https://github.com/jet/FsBlog/tree/master/Code/content/layouts/page.cshtml%22
  2. https://github.com/jet/FsBlog/tree/master/Code/content/layouts/post.cshtml
  3. https://github.com/tpetricek
  4. https://github.com/robertpi
  5. https://github.com/jet/FsBlog/issues/4

**Comment by rachelreese** [comment]
You rock. That was the issue -- AddedDate is being set in markdown, in the blog header, so it's a string. 

Once I updated several old packages I got a much more reasonable error. :) Thanks a ton.
